"""adiciona foreign key constraint com ondelete restrict para recurso

Revision ID: 0b14b748adde
Revises: dce332f35f0c
Create Date: 2025-12-04 08:57:44.250150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b14b748adde'
down_revision: Union[str, Sequence[str], None] = 'dce332f35f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Recurso', 'User', ['autor_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recurso', type_='foreignkey')
    # ### end Alembic commands ###
