"""Adiciona nome explicito para foreign key constraint de recurso autor_id

Revision ID: 1f578f61acec
Revises: 9e3741c50c6f
Create Date: 2025-12-04 10:12:22.609587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f578f61acec'
down_revision: Union[str, Sequence[str], None] = '9e3741c50c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_recurso_autor_id', 'Recurso', 'User', ['autor_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recurso_autor_id', 'Recurso', type_='foreignkey')
    # ### end Alembic commands ###
