"""inicial_completa

Revision ID: 2f0afd925ce9
Revises: 
Create Date: 2025-12-09 20:05:10.138430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f0afd925ce9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('perfil', sa.Enum('Gestor', 'Coordenador', 'Professor', 'Aluno', name='perfil'), nullable=False),
    sa.Column('status', sa.Enum('Ativo', 'Inativo', 'AguardandoAtivacao', name='status'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('path_img', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_table('Recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('visibilidade', sa.Enum('PUBLICO', 'PRIVADO', name='visibilidade'), nullable=False),
    sa.Column('estrutura', sa.Enum('UPLOAD', 'URL', 'NOTA', name='estruturarecurso'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('is_destaque', sa.Boolean(), nullable=False),
    sa.Column('visualizacoes', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('curtidas', sa.Integer(), nullable=False),
    sa.Column('conteudo_markdown', sa.Text(), nullable=True),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('url_externa', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['User.id'], name='fk_recurso_autor_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurso_autor_id', 'Recurso', ['autor_id'], unique=False)
    op.create_index('idx_recurso_criado_em', 'Recurso', ['criado_em'], unique=False)
    op.create_index('idx_recurso_estrutura', 'Recurso', ['estrutura'], unique=False)
    op.create_index('idx_recurso_visibilidade', 'Recurso', ['visibilidade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recurso_visibilidade', table_name='Recurso')
    op.drop_index('idx_recurso_estrutura', table_name='Recurso')
    op.drop_index('idx_recurso_criado_em', table_name='Recurso')
    op.drop_index('idx_recurso_autor_id', table_name='Recurso')
    op.drop_table('Recurso')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
