"""banco inicial com user

Revision ID: 3300110f2635
Revises: 
Create Date: 2025-11-30 20:00:52.094545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3300110f2635'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('Gestor', 'Coordenador', 'Professor', 'Aluno', name='perfil'), nullable=False),
    sa.Column('status', sa.Enum('Ativo', 'Inativo', name='status'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('path_img', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
