"""schema completo

Revision ID: 3c3c48bdf1ba
Revises: ae3824f0c9b9
Create Date: 2025-12-20 14:15:34.405285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c3c48bdf1ba'
down_revision: Union[str, Sequence[str], None] = 'ae3824f0c9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tag_nome'), 'Tag', ['nome'], unique=True)
    op.create_table('Recurso_Tag',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['Recurso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recurso_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recurso_Tag')
    op.drop_index(op.f('ix_Tag_nome'), table_name='Tag')
    op.drop_table('Tag')
    # ### end Alembic commands ###
