"""Atualiza migration para recriar FK com nome e ondelete RESTRICT

Revision ID: 6bc647afd908
Revises: a42dcb434455
Create Date: 2025-12-04 10:21:19.404751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bc647afd908'
down_revision: Union[str, Sequence[str], None] = 'a42dcb434455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
