"""explicita ondelete RESTRICT em autor_id de Recurso

Revision ID: 9e3741c50c6f
Revises: a937ab814262
Create Date: 2025-12-04 09:32:49.923185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e3741c50c6f'
down_revision: Union[str, Sequence[str], None] = 'a937ab814262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Recurso_autor_id_fkey'), 'Recurso', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('Recurso_autor_id_fkey'), 'Recurso', 'User', ['autor_id'], ['id'])
    # ### end Alembic commands ###
