"""Remove duplicata de foreign key, mantem apenas a constraint nomeada

Revision ID: a42dcb434455
Revises: 1f578f61acec
Create Date: 2025-12-04 10:13:47.860284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a42dcb434455'
down_revision: Union[str, Sequence[str], None] = '1f578f61acec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Recurso_autor_id_fkey'), 'Recurso', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('Recurso_autor_id_fkey'), 'Recurso', 'User', ['autor_id'], ['id'])
    # ### end Alembic commands ###
