"""adiciona indices de performance para tabela recurso

Revision ID: a937ab814262
Revises: 0b14b748adde
Create Date: 2025-12-04 09:01:45.133410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a937ab814262'
down_revision: Union[str, Sequence[str], None] = '0b14b748adde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_recurso_autor_id', 'Recurso', ['autor_id'], unique=False)
    op.create_index('idx_recurso_criado_em', 'Recurso', ['criado_em'], unique=False)
    op.create_index('idx_recurso_estrutura', 'Recurso', ['estrutura'], unique=False)
    op.create_index('idx_recurso_visibilidade', 'Recurso', ['visibilidade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recurso_visibilidade', table_name='Recurso')
    op.drop_index('idx_recurso_estrutura', table_name='Recurso')
    op.drop_index('idx_recurso_criado_em', table_name='Recurso')
    op.drop_index('idx_recurso_autor_id', table_name='Recurso')
    # ### end Alembic commands ###
