"""cria tabela recurso

Revision ID: dce332f35f0c
Revises: 3300110f2635
Create Date: 2025-12-04 07:50:43.047867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dce332f35f0c'
down_revision: Union[str, Sequence[str], None] = '3300110f2635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('visibilidade', sa.Enum('PUBLICO', 'PRIVADO', name='visibilidade'), nullable=False),
    sa.Column('estrutura', sa.Enum('UPLOAD', 'URL', 'NOTA', name='estruturarecurso'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('is_destaque', sa.Boolean(), nullable=False),
    sa.Column('visualizacoes', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('curtidas', sa.Integer(), nullable=False),
    sa.Column('conteudo_markdown', sa.Text(), nullable=True),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('url_externa', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recurso')
    # ### end Alembic commands ###
