"""Cria tabelas Playlist e PlaylistRecurso para gerenciamento de listas de recursos

Revision ID: f1a2b3c4d5e6
Revises: 6bc647afd908
Create Date: 2025-12-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, Sequence[str], None] = '6bc647afd908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['User.id'], ondelete='RESTRICT', name='fk_playlist_autor_id'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('idx_playlist_autor_id', 'Playlist', ['autor_id'], unique=False)
    op.create_index('idx_playlist_criado_em', 'Playlist', ['criado_em'], unique=False)
    
    op.create_table('PlaylistRecurso',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['Playlist.id'], ondelete='CASCADE', name='fk_playlist_recurso_playlist_id'),
    sa.ForeignKeyConstraint(['recurso_id'], ['Recurso.id'], ondelete='CASCADE', name='fk_playlist_recurso_recurso_id'),
    sa.PrimaryKeyConstraint('playlist_id', 'recurso_id')
    )
    
    op.create_index('idx_playlist_recurso_playlist_id', 'PlaylistRecurso', ['playlist_id'], unique=False)
    op.create_index('idx_playlist_recurso_recurso_id', 'PlaylistRecurso', ['recurso_id'], unique=False)
    op.create_index('idx_playlist_recurso_ordem', 'PlaylistRecurso', ['playlist_id', 'ordem'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_playlist_recurso_ordem', table_name='PlaylistRecurso')
    op.drop_index('idx_playlist_recurso_recurso_id', table_name='PlaylistRecurso')
    op.drop_index('idx_playlist_recurso_playlist_id', table_name='PlaylistRecurso')
    op.drop_table('PlaylistRecurso')
    
    op.drop_index('idx_playlist_criado_em', table_name='Playlist')
    op.drop_index('idx_playlist_autor_id', table_name='Playlist')
    op.drop_table('Playlist')
    # ### end Alembic commands ###
